In [1]:
#INSTALAR LIBRERIAS
%pip install pandas
%pip install numpy
%pip install matplotlib
%pip install seaborn
%pip install openpyxl

Requirement already satisfied: pandas in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (2.3.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: matplotlib in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (2.3.2)
Requirement already satisfied: packaging>=20.0 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: seaborn in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.2)
Requirement already satisfied: pandas>=1.2 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (2.3.1)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from seaborn) (3.10.5)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.59.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\vbece\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\vbece\appdata\local\programs\python\python313\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Convertir en dataframe el archivo CSV limpio con las variables de interés (50 columnas)
df = pd.read_csv("Bergamo_Italia.csv")
df.head(4)

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
0,0,city scrape,Mo's Cozy Cabana,The cabana is just a moments walk to 'The Spli...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.82,4.83,4.79,4.96,4.94,4.92,4.88,NaN,f,4
1,1,city scrape,"Seaside Villas 4 2nd Flr - Pool, Beach, Jacuzzi","Right on the beach, this building is in a prim...",604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.82,4.92,4.87,4.92,4.90,4.99,4.71,NaN,t,18
2,2,city scrape,Valarosa - Sweet cottage,Valarosa is on Avenida Chechem in a popular re...,604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.60,4.72,4.40,4.86,4.90,4.60,4.56,NaN,t,18
3,3,city scrape,"Toucan-kit, ac, wifi, bike, tropical gardens, ...","LOVE this area of Placencia; quiet, day & nigh...",733857,2011-06-23,within an hour,100%,f,"['email', 'phone']",...,4.86,4.89,4.97,4.92,4.95,4.81,4.86,NaN,t,5

In [4]:
#Carga de CSV original 
df_original= pd.read_csv("listings.csv")
df_original.head(4)

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,36690,https://www.airbnb.com/rooms/36690,20250323033851,2025-03-23,city scrape,Mo's Cozy Cabana,The Cozy Cabana is a funky & cozy studio locat...,The cabana is just a moments walk to 'The Spli...,https://a0.muscache.com/pictures/hosting/Hosti...,157752,...,4.94,4.92,4.88,NaN,f,4,4,0,0,2.59
1,120115,https://www.airbnb.com/rooms/120115,20250323033851,2025-03-23,city scrape,"Seaside Villas 4 2nd Flr - Pool, Beach, Jacuzzi",NaN,"Right on the beach, this building is in a prim...",https://a0.muscache.com/pictures/miso/Hosting-...,604999,...,4.90,4.99,4.71,NaN,t,18,18,0,0,0.75
2,120116,https://www.airbnb.com/rooms/120116,20250323033851,2025-03-23,city scrape,Valarosa - Sweet cottage,Charming one bedroom home set in the trees on ...,Valarosa is on Avenida Chechem in a popular re...,https://a0.muscache.com/pictures/323c28c8-c4e2...,604999,...,4.90,4.60,4.56,NaN,t,18,18,0,0,0.79
3,152512,https://www.airbnb.com/rooms/152512,20250323033851,2025-03-23,city scrape,"Toucan-kit, ac, wifi, bike, tropical gardens, ...","Casa Placencia's Toucan, w/12 ft ceilings & sp...","LOVE this area of Placencia; quiet, day & nigh...",https://a0.muscache.com/pictures/hosting/Hosti...,733857,...,4.95,4.81,4.86,NaN,t,5,4,0,0,0.45

APLICACIÓN DE FILTROS

In [ ]:
#FiltroA = Resgisto de 5 "host_name" diferentes 
#En este caso se utilizó la base de datos original, ya que en la base de datos tratada decidí eliminar por temas más prácticos esta columna, para los siguientes filtros no fue necesario utilizar la base de datos original. 
#Se utilizó la función "value_counts()" para contar la cantidad de veces que se repite cada "host_name" y luego se utilizó "head(5)" para mostrar los 5 más frecuentes.
host_name = df_original['host_name'].value_counts().head(5)
host_name

host_name
Vacasa Belize    204
Dwayne L          99
David             39
Nellie            35
Kathleen          35
Name: count, dtype: int64

In [10]:
#Exportar filtro "host_name" a CSV
host_name.to_csv("FiltroA.csv")

In [ ]:
#FiltroB = Resgistro de los host que se hallan unido a Airbnb después del año 2020
#Se utilizó el filtro de comporación para seleccionar las fechas posteriores al 31 de diciembre de 2020.
incorporacion = df[df['host_since'] > '2020-12-31']
incorporacion

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
862,862,city scrape,Casita Anita: Adorable Studio in Caye Caulker,NaN,448967763,2022-03-10,NaN,NaN,f,"['email', 'phone']",...,4.81,4.83,4.79,4.90,4.79,4.90,4.71,NaN,f,1
1313,1313,city scrape,Oceanfront Condo C2- Pool/Jacuzzi/heart of Town,Diamante is located on the South end of town a...,435219161,2021-12-08,NaN,NaN,f,['phone'],...,5.00,4.70,5.00,4.80,5.00,5.00,4.90,NaN,t,1
1482,1482,city scrape,Borland Island Cabin,"Close to L K MARKET in Bahia Puesta del Sol,, ...",382875785,2021-01-03,within an hour,100%,f,"['email', 'phone']",...,4.74,4.68,4.83,4.96,5.00,4.26,4.70,NaN,f,1
1517,1517,city scrape,Modern apartment with pool and rooftop lounge ...,NaN,572875223,2024-04-17,within an hour,100%,f,"['email', 'phone']",...,4.97,4.94,4.94,4.97,4.97,4.72,4.97,NaN,t,6
1519,1519,city scrape,"Slice of Paradise - peaceful, tranquil, charming.",NaN,389820570,2021-02-23,within an hour,90%,t,"['email', 'phone']",...,4.81,4.74,4.69,4.85,4.83,4.86,4.80,NaN,f,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3424,3424,city scrape,Alexander Guest House - 3 Bedroom,NaN,667509750,2024-12-17,within a few hours,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,6
3425,3425,city scrape,Tree Fort Glamping in Belize!,NaN,684428729,2025-03-15,NaN,NaN,f,"['email', 'phone']",...,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,f,1
3430,3430,city scrape,The Smiths Luxe Residences | U2,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3431,3431,city scrape,The Smiths Luxe Residences | U3,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3432,3432,city scrape,"Ocean Crush- Beachfront, Pool, Tiki Bar, Pier",Located on the stunning eastern coast of Beliz...,565510231,2024-03-05,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1

In [ ]:
#Corroboración que el filtro se haya aplicado correctamente
#Se utilizó la función "min()" para verificar que la fecha mínima en la columna "host_since" sea posterior al 31 de diciembre de 2020.
incorporacion['host_since'].min()

'2021-01-03'

In [11]:
#Exportar filtro incorporacion a CSV
incorporacion.to_csv("FiltroB.csv")

In [ ]:
#Verificación de los tiempos de respuesta de los host
#Se utilizó la función "value_counts()" para contar la cantidad de veces que se repite cada tiempo de respuesta.
host_response_time = df['host_response_time'].value_counts()
host_response_time

host_response_time
within an hour        2615
within a few hours     175
within a day           135
a few days or more      50
Name: count, dtype: int64

In [ ]:
#FiltroC = Registro de los host que responden a más tardar en 1 día
#Se utilizó el filtro lógico con contenedores para filtrar los tiempos de respuesta "within an hour", "within a few hours" y "within a day", unidos por el operador OR "|".
respuesta = df[(df['host_response_time'] == 'within an hour') | (df['host_response_time'] == 'within a day') | (df['host_response_time'] == 'within a few hours')]
respuesta

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
0,0,city scrape,Mo's Cozy Cabana,The cabana is just a moments walk to 'The Spli...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.82,4.83,4.79,4.96,4.94,4.92,4.88,NaN,f,4
1,1,city scrape,"Seaside Villas 4 2nd Flr - Pool, Beach, Jacuzzi","Right on the beach, this building is in a prim...",604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.82,4.92,4.87,4.92,4.90,4.99,4.71,NaN,t,18
2,2,city scrape,Valarosa - Sweet cottage,Valarosa is on Avenida Chechem in a popular re...,604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.60,4.72,4.40,4.86,4.90,4.60,4.56,NaN,t,18
3,3,city scrape,"Toucan-kit, ac, wifi, bike, tropical gardens, ...","LOVE this area of Placencia; quiet, day & nigh...",733857,2011-06-23,within an hour,100%,f,"['email', 'phone']",...,4.86,4.89,4.97,4.92,4.95,4.81,4.86,NaN,t,5
4,4,city scrape,rent a private room in a house,"Quiet neighbourhood, close to shopping centre,...",735525,2011-06-23,within a day,67%,f,"['email', 'phone']",...,4.62,4.92,4.77,4.62,4.69,4.62,4.77,NaN,f,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3428,3428,city scrape,3 Bedroom condo in San Pedro,NaN,209765871,2018-08-15,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,7
3429,3429,city scrape,Mayatai Beach Villa - Elegant 2 Bedroom Beachf...,NaN,72483617,2016-05-17,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,33
3430,3430,city scrape,The Smiths Luxe Residences | U2,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3431,3431,city scrape,The Smiths Luxe Residences | U3,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3432,3432,city scrape,"Ocean Crush- Beachfront, Pool, Tiki Bar, Pier",Located on the stunning eastern coast of Beliz...,565510231,2024-03-05,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1

In [26]:
#Verificación de los tiempos de respuesta de los host en el FiltroC
c = respuesta['host_response_time'].value_counts()
c

host_response_time
within an hour        2615
within a few hours     175
within a day           135
Name: count, dtype: int64

In [27]:
#Exportar filtro respuesta a CSV
respuesta.to_csv("FiltroC.csv")

In [ ]:
#FiltroD = Los registros de las filas “Múltiplos de 200… (400, 600, 800, etc.)”
#Se utilizó la función "iloc" para seleccionar las filas que son múltiplos de 200, utilizando el fomato de columnas consecutivas, es decir, comenzando desde la fila 0 y seleccionando cada 200 filas.
multiplos = df.iloc[::200, :]
multiplos

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
0,0,city scrape,Mo's Cozy Cabana,The cabana is just a moments walk to 'The Spli...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.82,4.83,4.79,4.96,4.94,4.92,4.88,NaN,f,4
200,200,city scrape,"BEACH and OCEAN VIEW! SECRET BEACH CABANAS, Green",Our cabanas are a steps to the crystal blue wa...,55546205,2016-01-21,within an hour,100%,t,"['email', 'phone']",...,4.88,4.88,4.93,4.93,4.98,4.86,4.86,NaN,f,4
400,400,city scrape,Hidden Treasure Vacation Home: Bayblue Cottage,Bayblue is located on the north west side of o...,127097068,2017-04-22,within an hour,100%,t,"['email', 'phone']",...,4.99,4.96,5.00,4.99,4.96,4.88,4.95,NaN,f,4
600,600,city scrape,Sail away on a vintage pirate sailboat!,The Old Belize Marina sits right on the George...,57457406,2016-02-04,within a day,100%,f,"['email', 'phone']",...,4.79,4.88,4.93,4.92,4.96,4.76,4.81,NaN,t,1
800,800,city scrape,The Great House Inn,The Great House Inn is located in the historic...,217770661,2018-09-28,within an hour,100%,f,"['email', 'phone']",...,4.70,4.83,4.87,4.84,4.74,4.72,4.70,NaN,f,1
1000,1000,city scrape,Charming 1BR Mayan Falls 2nd-Floor | Balcony,NaN,76414486,2016-06-07,within an hour,98%,f,"['email', 'phone']",...,4.28,4.36,4.40,4.47,4.62,3.77,4.26,NaN,t,204
1200,1200,city scrape,2 The Beach House - Condo Downtown San Pedro,Our location is in the heart of San Pedro Town...,59990092,2016-02-22,within an hour,100%,t,"['email', 'phone']",...,4.92,4.93,4.96,4.87,4.98,4.90,4.91,NaN,f,5
1400,1400,city scrape,1BR | Patio | W/D | Enclosed Yard,NaN,76414486,2016-06-07,within an hour,98%,f,"['email', 'phone']",...,4.57,4.71,4.71,5.00,5.00,4.43,4.57,NaN,t,204
1600,1600,previous scrape,Mahogany Bay Village Tiny Homes with Private Pool,"Enjoy a morning latte at the Rum and Bean, the...",72404857,2016-05-16,within an hour,100%,f,"['email', 'phone', 'work_email']",...,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,t,3
1800,1800,previous scrape,Suite-Designer-Ensuite with Shower-Treetops Suite,"Overlooking the Caribbean Sea, The Tree Tops s...",427948310,2021-10-18,within a day,50%,f,"['email', 'phone']",...,5.00,5.00,5.00,5.00,5.00,4.33,4.33,NaN,t,8
2000,2000,city scrape,All shades of Blu,North Caye Caulker is located just a 10 Minute...,249277530,2019-03-16,within an hour,100%,t,"['email', 'phone']",...,4.95,4.98,4.98,4.95,4.98,4.92,4.87,NaN,f,5
2200,2200,previous scrape,Sunset Beach Casita | San Pedro Sea Side,NaN,165897955,2018-01-04,within an hour,100%,t,"['email', 'phone', 'work_email']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,17
2400,2400,city scrape,Mirasol Nth: Steps From Beach-Heart of Placencia,NaN,261868426,2019-05-14,within an hour,100%,t,"['email', 'phone']",...,4.79,4.74,4.79,4.95,4.89,4.89,4.79,NaN,t,99
2600,2600,city scrape,Hillside Cabaña,There is no neighborhood here. We are 5.5 mile...,545904918,2023-11-10,within an hour,100%,t,"['email', 'phone']",...,5.00,5.00,5.00,5.00,4.33,5.00,5.00,NaN,t,4
2800,2800,previous scrape,"Tropical Luxury: 3 Bedroom Condo, Pool View","Your surroundings: garden, pool. Activities yo...",562348783,2024-02-16,within an hour,90%,f,"['email', 'phone']",...,4.00,3.00,4.00,4.00,3.00,4.00,4.00,NaN,t,8
3000,3000,city scrape,Island Magic Rooftop Villas,NaN,241061744,2019-02-04,within an hour,100%,t,"['email', 'phone']",...,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,t,11
3200,3200,city scrape,Leatherback Studio at Secret Beach,NaN,473525368,2022-08-05,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,13
3400,3400,city scrape,Mariposa Hibiscus Bungalow,NaN,515682824,2023-05-20,NaN,NaN,NaN,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1

In [29]:
#Exportar filtro multiplos a CSV
multiplos.to_csv("FiltroD.csv")

In [ ]:
#Verificación de los tipos de cuartos
#Se utilizó la función "value_counts()" para contar la cantidad de veces que se repite cada tipo de cuarto.
room_type = df['room_type'].value_counts()
room_type

room_type
Entire home/apt    2414
Private room        903
Hotel room           87
Shared room          29
Name: count, dtype: int64

In [31]:
#FiltroE = Los registros de los tipos de cuarto: “Entire home”  y “Private room”
#Se utilizó el filtro lógico con contenedores para filtrar los tipos de cuarto "Entire home/apt" y "Private room", unidos por el operador OR "|".
cuarto = df[(df['room_type'] == 'Entire home/apt') | (df['room_type'] == 'Private room')]
cuarto

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
0,0,city scrape,Mo's Cozy Cabana,The cabana is just a moments walk to 'The Spli...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.82,4.83,4.79,4.96,4.94,4.92,4.88,NaN,f,4
1,1,city scrape,"Seaside Villas 4 2nd Flr - Pool, Beach, Jacuzzi","Right on the beach, this building is in a prim...",604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.82,4.92,4.87,4.92,4.90,4.99,4.71,NaN,t,18
2,2,city scrape,Valarosa - Sweet cottage,Valarosa is on Avenida Chechem in a popular re...,604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.60,4.72,4.40,4.86,4.90,4.60,4.56,NaN,t,18
3,3,city scrape,"Toucan-kit, ac, wifi, bike, tropical gardens, ...","LOVE this area of Placencia; quiet, day & nigh...",733857,2011-06-23,within an hour,100%,f,"['email', 'phone']",...,4.86,4.89,4.97,4.92,4.95,4.81,4.86,NaN,t,5
4,4,city scrape,rent a private room in a house,"Quiet neighbourhood, close to shopping centre,...",735525,2011-06-23,within a day,67%,f,"['email', 'phone']",...,4.62,4.92,4.77,4.62,4.69,4.62,4.77,NaN,f,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3428,3428,city scrape,3 Bedroom condo in San Pedro,NaN,209765871,2018-08-15,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,7
3429,3429,city scrape,Mayatai Beach Villa - Elegant 2 Bedroom Beachf...,NaN,72483617,2016-05-17,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,33
3430,3430,city scrape,The Smiths Luxe Residences | U2,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3431,3431,city scrape,The Smiths Luxe Residences | U3,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3432,3432,city scrape,"Ocean Crush- Beachfront, Pool, Tiki Bar, Pier",Located on the stunning eastern coast of Beliz...,565510231,2024-03-05,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1

In [ ]:
#Verificación de los tipos de cuartos en el FiltroE
d = cuarto['room_type'].value_counts()
d

room_type
Entire home/apt    2414
Private room        903
Name: count, dtype: int64

In [33]:
#Exportar filtro cuarto a CSV
cuarto.to_csv("FiltroE.csv")

In [34]:
#Verificación el número de camas
#Se utilizó la función "value_counts()" para contar la cantidad de veces que se repite un número de camas.
beds = df['beds'].value_counts()
beds

beds
1.0     989
2.0     847
3.0     425
4.0     234
5.0     128
6.0     101
0.0      38
8.0      36
7.0      26
9.0      21
10.0     15
11.0      4
28.0      4
13.0      3
14.0      2
17.0      2
18.0      1
12.0      1
16.0      1
26.0      1
Name: count, dtype: int64

In [52]:
#Filtro F = Los registros que “a lo mucho cuenten con 4 camas”
#Se utilizó el filtro de comparación para filtrar los registros que tienen 4 camas o menos.
camas = df[df['beds'] <= 4]
camas

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
0,0,city scrape,Mo's Cozy Cabana,The cabana is just a moments walk to 'The Spli...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.82,4.83,4.79,4.96,4.94,4.92,4.88,NaN,f,4
1,1,city scrape,"Seaside Villas 4 2nd Flr - Pool, Beach, Jacuzzi","Right on the beach, this building is in a prim...",604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.82,4.92,4.87,4.92,4.90,4.99,4.71,NaN,t,18
2,2,city scrape,Valarosa - Sweet cottage,Valarosa is on Avenida Chechem in a popular re...,604999,2011-05-19,within an hour,100%,NaN,"['email', 'phone']",...,4.60,4.72,4.40,4.86,4.90,4.60,4.56,NaN,t,18
3,3,city scrape,"Toucan-kit, ac, wifi, bike, tropical gardens, ...","LOVE this area of Placencia; quiet, day & nigh...",733857,2011-06-23,within an hour,100%,f,"['email', 'phone']",...,4.86,4.89,4.97,4.92,4.95,4.81,4.86,NaN,t,5
4,4,city scrape,rent a private room in a house,"Quiet neighbourhood, close to shopping centre,...",735525,2011-06-23,within a day,67%,f,"['email', 'phone']",...,4.62,4.92,4.77,4.62,4.69,4.62,4.77,NaN,f,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3428,3428,city scrape,3 Bedroom condo in San Pedro,NaN,209765871,2018-08-15,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,7
3429,3429,city scrape,Mayatai Beach Villa - Elegant 2 Bedroom Beachf...,NaN,72483617,2016-05-17,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,33
3430,3430,city scrape,The Smiths Luxe Residences | U2,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3431,3431,city scrape,The Smiths Luxe Residences | U3,NaN,680517041,2025-02-23,within an hour,100%,f,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,3
3432,3432,city scrape,"Ocean Crush- Beachfront, Pool, Tiki Bar, Pier",Located on the stunning eastern coast of Beliz...,565510231,2024-03-05,within an hour,100%,f,['phone'],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,1

In [53]:
#Verificación el número de camas en el FiltroF
f = camas['beds'].value_counts()
f

beds
1.0    989
2.0    847
3.0    425
4.0    234
0.0     38
Name: count, dtype: int64

In [54]:
#Exportar filtro camas a CSV
camas.to_csv("FiltroF.csv")

In [55]:
#Verificación de los tipos de host
host = df['host_is_superhost'].value_counts()
host

host_is_superhost
f    1855
t    1508
Name: count, dtype: int64

In [56]:
#FiltroG = Los registros que “sean superhost”
#Se utilizó el filtro lógico para filtrar los registros que tienen el valor "t" en la columna "host_is_superhost".
superhost = df[df['host_is_superhost'] == 't']
superhost

,Unnamed: 0,source,name,neighborhood_overview,host_id,host_since,host_response_time,host_response_rate,host_is_superhost,host_verifications,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count
0,0,city scrape,Mo's Cozy Cabana,The cabana is just a moments walk to 'The Spli...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.82,4.83,4.79,4.96,4.94,4.92,4.88,NaN,f,4
13,13,city scrape,Casa Belize - Cozy Studio Apartment,This neighborhood is made up of mainly profess...,2917510,2012-07-12,within an hour,100%,t,"['email', 'phone']",...,4.87,4.86,4.89,4.95,5.00,4.54,4.68,NaN,f,6
14,14,city scrape,Sunny Cabana,The cabana is located just outside the village...,157752,2010-07-03,within an hour,100%,t,"['email', 'phone']",...,4.79,4.90,4.73,4.91,4.95,4.74,4.82,NaN,f,4
17,17,city scrape,Home Away From Home Desirable Area,This neighborhood is made up of mainly profess...,2917510,2012-07-12,within an hour,100%,t,"['email', 'phone']",...,4.90,4.96,4.96,4.97,5.00,4.71,4.91,NaN,f,6
18,18,city scrape,Comfy Cabana Tropical Caye Caulker,Everything on the island is within walking dis...,2267459,2012-05-01,within an hour,100%,t,"['email', 'phone']",...,4.78,4.81,4.84,4.84,4.82,4.69,4.77,NaN,t,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3406,3406,city scrape,Luxurious 2 Bed 2 Bath with Pool in Belize City,NaN,8554313,2013-08-31,within an hour,100%,t,"['email', 'phone', 'work_email']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,15
3407,3407,city scrape,"UpperWest Cabins (San Ignacio, Cayo) with AC&W...",NaN,202369165,2018-07-14,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,4
3417,3417,city scrape,Slack Tide - 2BR House at Secret Beach,NaN,473525368,2022-08-05,within an hour,100%,t,"['email', 'phone']",...,5.00,5.00,5.00,5.00,5.00,5.00,5.00,NaN,t,13
3426,3426,city scrape,King Bungalow- Weezie's Hotel,NaN,6334784,2013-05-11,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,13
3429,3429,city scrape,Mayatai Beach Villa - Elegant 2 Bedroom Beachf...,NaN,72483617,2016-05-17,within an hour,100%,t,"['email', 'phone']",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,33

In [57]:
#Verificación de los tipos de host
g = superhost['host_is_superhost'].value_counts()
g

host_is_superhost
t    1508
Name: count, dtype: int64

In [58]:
#Exportar filtro superhost a CSV
superhost.to_csv("FiltroG.csv")

In [60]:
#Verificamos el orden de las columnas
df.columns

Index(['Unnamed: 0', 'source', 'name', 'neighborhood_overview', 'host_id',
       'host_since', 'host_response_time', 'host_response_rate',
       'host_is_superhost', 'host_verifications', 'host_has_profile_pic',
       'host_identity_verified', 'neighbourhood_cleansed',
       'neighbourhood_group_cleansed', 'latitude', 'longitude',
       'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms',
       'beds', 'amenities', 'price', 'minimum_nights', 'maximum_nights',
       'has_availability', 'availability_30', 'availability_60',
       'availability_90', 'availability_365', 'calendar_last_scraped',
       'number_of_reviews', 'number_of_reviews_ltm', 'number_of_reviews_l30d',
       'availability_eoy', 'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count'],
      dtype='object')

In [ ]:
#FiltroH = Los registros de las columnas “impares”
#Se utilizó la función "iloc" para seleccionar las columnas impares, comenzando desde la columna 1 (segunda columna) y seleccionando cada 2 columnas, se utilizó ":" para seleccionar todas las filas y "1::2" para seleccionar las columnas impares.
#Se inicio desde la segunda columna, ya que la primera columna es la 0 y "sources" es la primera columna seleccionada del dataframe original.
impares = df.iloc[:, 1::2]
impares

,source,neighborhood_overview,host_since,host_response_rate,host_verifications,host_identity_verified,neighbourhood_group_cleansed,longitude,room_type,bathrooms,...,calendar_last_scraped,number_of_reviews_ltm,availability_eoy,estimated_occupancy_l365d,first_review,review_scores_rating,review_scores_cleanliness,review_scores_communication,review_scores_value,instant_bookable
0,city scrape,The cabana is just a moments walk to 'The Spli...,2010-07-03,100%,"['email', 'phone']",t,Belize,-88.024740,Entire home/apt,1.0,...,2025-03-23,36,159,216,2010-08-13,4.82,4.79,4.94,4.88,f
1,city scrape,"Right on the beach, this building is in a prim...",2011-05-19,100%,"['email', 'phone']",t,Belize,-88.023950,Entire home/apt,2.0,...,2025-03-23,10,205,60,2017-04-18,4.82,4.87,4.90,4.71,t
2,city scrape,Valarosa is on Avenida Chechem in a popular re...,2011-05-19,100%,"['email', 'phone']",t,Belize,-88.028534,Entire home/apt,1.0,...,2025-03-23,12,262,72,2016-02-24,4.60,4.40,4.90,4.56,t
3,city scrape,"LOVE this area of Placencia; quiet, day & nigh...",2011-06-23,100%,"['email', 'phone']",f,Stann Creek,-88.368640,Entire home/apt,1.0,...,2025-03-23,1,89,14,2011-11-28,4.86,4.97,4.95,4.86,t
4,city scrape,"Quiet neighbourhood, close to shopping centre,...",2011-06-23,67%,"['email', 'phone']",t,Cayo,-88.767710,Private room,1.0,...,2025-03-23,2,284,12,2016-03-30,4.62,4.77,4.69,4.77,f
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3428,city scrape,NaN,2018-08-15,100%,['phone'],t,Belize,-87.977794,Private room,3.0,...,2025-03-23,0,276,0,NaN,NaN,NaN,NaN,NaN,t
3429,city scrape,NaN,2016-05-17,100%,"['email', 'phone']",t,Stann Creek,-88.361123,Entire home/apt,3.0,...,2025-03-23,0,249,0,NaN,NaN,NaN,NaN,NaN,t
3430,city scrape,NaN,2025-02-23,100%,"['email', 'phone']",t,Belize,-88.280021,Entire home/apt,1.0,...,2025-03-23,0,1,0,NaN,NaN,NaN,NaN,NaN,t
3431,city scrape,NaN,2025-02-23,100%,"['email', 'phone']",t,Belize,-88.279876,Entire home/apt,1.0,...,2025-03-23,0,2,0,NaN,NaN,NaN,NaN,NaN,t
3432,city scrape,Located on the stunning eastern coast of Beliz...,2024-03-05,100%,['phone'],t,Stann Creek,-88.332928,Entire home/apt,1.0,...,2025-03-23,0,284,0,NaN,NaN,NaN,NaN,NaN,t

In [71]:
#Exportar filtro impares a CSV
impares.to_csv("FiltroH.csv")